### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by SketchySwift** [KittenYang/GooeyTabbar#2]
How do I add items to it? like the dribbble shot

**Comment by seyhunak** [comment]
+1 /cc @KittenYang

**Comment by AnnieNinaJoyceV** [comment]
Any update on this, please?

**Comment by SketchySwift** [comment]
What's the point of making this library if there is no use for it? @KittenYang Can we add items to this?

**Comment by AnnieNinaJoyceV** [comment]
I tried modifying the `TabbarMenu.swift` class to add menu items dynamically. Unfortunately all the items added takes same frame and moreover the views are getting duplicated overtime the menu is opened. So I created a delegate to indicate the controller when the menu is opened/closed. At that time, from the controller I added menu items. Do you think/suggest any other solutions?

Here is my output
![gooeymenutrial](https://cloud.githubusercontent.com/assets/7369485/15893662/ca8015b4-2d9e-11e6-88b6-a5eb2721cbe4.gif)

P.S:- I played around almost all the parameters, shrunk the menu height, reduced animation duration and something else I suppose.

**Comment by SketchySwift** [comment]
@AnnieNinaJoyceV Magnificent! How did you do it? Do you mind uploading it to github? Or maybe pasting the code/solution here.

**Comment by AnnieNinaJoyceV** [comment]
@HardcoreIOS Here is the code - https://www.dropbox.com/s/p6801waedg7q0np/GooeyTabbar-master_Modified.zip?dl=0
P.S: The implementation might be ugly :) I just wanted to check the possibility of adding items. In return if you improve the implementation can you share the code as well?

**Comment by SketchySwift** [comment]
@AnnieNinaJoyceV Thank you so much! I'll try what I can do!

**Comment by KittenYang** [comment]
pls read the code.it's simple but I have no spare time to do this,you can try it yourself.
